services:
  flood:
    hostname: flood
    image: jesec/flood
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    user: 1000:1000
    environment:
      HOME: /config
    volumes:
      - /docker/flood/config:/config
      - /mnt/storage_sata/portainer/flood:/data
      - /mnt/storage_sata/:/storage_sata
    networks:
      - npm_net
networks:
  npm_net:
    external: true
